In [ ]:
import numpy as np

x = np.array([1.0, 2.0, 3.0])
print(x)  # [1. 2. 3.]

type(x)  # numpy.ndarray

[1. 2. 3.]


numpy.ndarray

In [8]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
x + y  # array([3., 6., 9.])

x - y  # array([-1., -2., -3.])

x * y  # array([ 2.,  8., 18.])

x / y  # array([0.5, 0.5, 0.5])

array([0.5, 0.5, 0.5])

In [ ]:
x = np.array([1.0, 2.0, 3.0])
x / 2.0  # array([0.5, 1. , 1.5])

array([0.5, 1. , 1.5])

In [ ]:
A = np.array([[1, 2], [3, 4]])
print(A)
"""
[[1 2]
 [3 4]]
"""

A.shape  # (2, 2)

A.dtype  # dtype('int64')

[[1 2]
 [3 4]]


dtype('int64')

In [16]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[3, 0], [0, 6]])
A + B
"""
array([[ 4,  2],
       [ 3, 10]])
"""

A * B
"""
array([[ 3,  0],
       [ 0, 24]])
"""

'\narray([[ 3,  0],\n       [ 0, 24]])\n'