In [2]:
import numpy as np

x = np.array([1.0, 2.0, 3.0])
print(x)  # [1. 2. 3.]

type(x)  # numpy.ndarray

[1. 2. 3.]


numpy.ndarray

In [3]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
x + y  # array([3., 6., 9.])

x - y  # array([-1., -2., -3.])

x * y  # array([ 2.,  8., 18.])

x / y  # array([0.5, 0.5, 0.5])

array([0.5, 0.5, 0.5])

In [4]:
x = np.array([1.0, 2.0, 3.0])
x / 2.0  # array([0.5, 1. , 1.5])

array([0.5, 1. , 1.5])

In [5]:
A = np.array([[1, 2], [3, 4]])
print(A)
"""
[[1 2]
 [3 4]]
"""

A.shape  # (2, 2)

A.dtype  # dtype('int64')

[[1 2]
 [3 4]]


dtype('int64')

In [6]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[3, 0], [0, 6]])
A + B
"""
array([[ 4,  2],
       [ 3, 10]])
"""

A * B
"""
array([[ 3,  0],
       [ 0, 24]])
"""

'\narray([[ 3,  0],\n       [ 0, 24]])\n'

In [ ]:
A = np.array([[1, 2], [3, 4]])
A * 10
"""
array([[10, 20],
       [30, 40]])
"""

array([[10, 20],
       [30, 40]])

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])
A * B
"""
array([[10, 40],
       [30, 80]])
"""

array([[10, 40],
       [30, 80]])

In [ ]:
X = np.array(
    [
        [51, 55],
        [14, 19],
        [0, 4],
    ]
)
print(X)
"""
[[51 55]
 [14 19]
 [ 0  4]]
"""

X[0]  # array([51, 55])

X[0][1]  # np.int64(55)

for row in X:
    print(row)
"""
[51 55]
[14 19]
[0 4]
"""

[[51 55]
 [14 19]
 [ 0  4]]


np.int64(55)

In [ ]:
X = X.flatten()
print(X)  # [51 55 14 19  0  4]

X[np.array([0, 2, 4])]  # array([51, 14,  0])

[51 55 14 19  0  4]


array([51, 14,  0])